// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Fcs.Campaign.FunctionalTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GestaoDeCampanhasFeature : object, Xunit.IClassFixture<GestaoDeCampanhasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gestão de campanhas", ("  Como GestorONG\r\n  Quero administrar campanhas\r\n  Para manter as iniciativas de " +
                "arrecadação atualizadas"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GestaoCampanhas.feature"
#line hidden
        
        public GestaoDeCampanhasFeature(GestaoDeCampanhasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar campanha sempre como ativa")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Criar campanha sempre como ativa")]
        public async System.Threading.Tasks.Task CriarCampanhaSempreComoAtiva()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar campanha sempre como ativa", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu criar uma campanha válida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve ter status 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("a campanha retornada deve estar com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("a campanha deve registrar o gestor autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("deve ser publicada a auditoria \"CampaignCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Rejeitar criação de campanha inválida")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Rejeitar criação de campanha inválida")]
        [Xunit.InlineDataAttribute("titulo", new string[0])]
        [Xunit.InlineDataAttribute("descricao", new string[0])]
        [Xunit.InlineDataAttribute("data final", new string[0])]
        [Xunit.InlineDataAttribute("intervalo", new string[0])]
        [Xunit.InlineDataAttribute("meta", new string[0])]
        public async System.Threading.Tasks.Task RejeitarCriacaoDeCampanhaInvalida(string campo, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("campo", campo);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rejeitar criação de campanha inválida", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
    await testRunner.WhenAsync(string.Format("eu criar uma campanha com \"{0}\" inválido", campo), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("a resposta deve ter status 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Impedir acesso administrativo sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Impedir acesso administrativo sem autenticação")]
        public async System.Threading.Tasks.Task ImpedirAcessoAdministrativoSemAutenticacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Impedir acesso administrativo sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.GivenAsync("que não estou autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 30
    await testRunner.WhenAsync("eu listar as campanhas administrativas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 31
    await testRunner.ThenAsync("a resposta deve ter status 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Impedir acesso administrativo sem a role GestorONG")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Impedir acesso administrativo sem a role GestorONG")]
        public async System.Threading.Tasks.Task ImpedirAcessoAdministrativoSemARoleGestorONG()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Impedir acesso administrativo sem a role GestorONG", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("que estou autenticado como \"Doador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 35
    await testRunner.WhenAsync("eu listar as campanhas administrativas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 36
    await testRunner.ThenAsync("a resposta deve ter status 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Editar campanha ativa")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Editar campanha ativa")]
        public async System.Threading.Tasks.Task EditarCampanhaAtiva()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar campanha ativa", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 40
    await testRunner.AndAsync("existe uma campanha com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 41
    await testRunner.WhenAsync("eu editar a campanha", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 42
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 43
    await testRunner.AndAsync("a campanha deve conter os dados atualizados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 44
    await testRunner.AndAsync("deve ser publicada a auditoria \"CampaignUpdated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não editar campanha encerrada")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Não editar campanha encerrada")]
        public async System.Threading.Tasks.Task NaoEditarCampanhaEncerrada()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não editar campanha encerrada", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 48
    await testRunner.AndAsync("existe uma campanha com status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 49
    await testRunner.WhenAsync("eu editar a campanha", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 50
    await testRunner.ThenAsync("a resposta deve ter status 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Retornar não encontrado ao editar campanha inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Retornar não encontrado ao editar campanha inexistente")]
        public async System.Threading.Tasks.Task RetornarNaoEncontradoAoEditarCampanhaInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retornar não encontrado ao editar campanha inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 54
    await testRunner.WhenAsync("eu editar uma campanha inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 55
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar campanha por identificador")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Consultar campanha por identificador")]
        public async System.Threading.Tasks.Task ConsultarCampanhaPorIdentificador()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar campanha por identificador", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 59
    await testRunner.AndAsync("existe uma campanha com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 60
    await testRunner.WhenAsync("eu consultar a campanha por identificador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 61
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 62
    await testRunner.AndAsync("a campanha consultada deve ser a campanha existente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Retornar não encontrado ao consultar campanha inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Retornar não encontrado ao consultar campanha inexistente")]
        public async System.Threading.Tasks.Task RetornarNaoEncontradoAoConsultarCampanhaInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retornar não encontrado ao consultar campanha inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 66
    await testRunner.WhenAsync("eu consultar uma campanha inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 67
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Alterar status de campanha ativa")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Alterar status de campanha ativa")]
        [Xunit.InlineDataAttribute("Completed", "CampaignCompleted", new string[0])]
        [Xunit.InlineDataAttribute("Canceled", "CampaignCanceled", new string[0])]
        public async System.Threading.Tasks.Task AlterarStatusDeCampanhaAtiva(string status, string auditoria, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            argumentsOfScenario.Add("auditoria", auditoria);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alterar status de campanha ativa", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 70
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 71
    await testRunner.AndAsync("existe uma campanha com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 72
    await testRunner.WhenAsync(string.Format("eu alterar o status da campanha para \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 73
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 74
    await testRunner.AndAsync(string.Format("o status retornado deve ser \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 75
    await testRunner.AndAsync(string.Format("deve ser publicada a auditoria \"{0}\"", auditoria), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Rejeitar transição de status inválida")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Rejeitar transição de status inválida")]
        [Xunit.InlineDataAttribute("Active", "Active", new string[0])]
        [Xunit.InlineDataAttribute("Completed", "Active", new string[0])]
        [Xunit.InlineDataAttribute("Completed", "Canceled", new string[0])]
        [Xunit.InlineDataAttribute("Canceled", "Active", new string[0])]
        [Xunit.InlineDataAttribute("Canceled", "Completed", new string[0])]
        public async System.Threading.Tasks.Task RejeitarTransicaoDeStatusInvalida(string inicial, string destino, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("inicial", inicial);
            argumentsOfScenario.Add("destino", destino);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rejeitar transição de status inválida", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 84
    await testRunner.AndAsync(string.Format("existe uma campanha com status \"{0}\"", inicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 85
    await testRunner.WhenAsync(string.Format("eu alterar o status da campanha para \"{0}\"", destino), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 86
    await testRunner.ThenAsync("a resposta deve ter status 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Rejeitar status desconhecido")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão de campanhas")]
        [Xunit.TraitAttribute("Description", "Rejeitar status desconhecido")]
        public async System.Threading.Tasks.Task RejeitarStatusDesconhecido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rejeitar status desconhecido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 97
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 98
    await testRunner.AndAsync("existe uma campanha com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 99
    await testRunner.WhenAsync("eu alterar o status da campanha para \"Unknown\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 100
    await testRunner.ThenAsync("a resposta deve ter status 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 101
    await testRunner.AndAsync("a resposta deve informar que os status válidos são \"Completed, Canceled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GestaoDeCampanhasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GestaoDeCampanhasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
