// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Fcs.Campaign.FunctionalTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ListagemDeCampanhasFeature : object, Xunit.IClassFixture<ListagemDeCampanhasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Listagem de campanhas", ("  Como cliente da API\r\n  Quero consultar campanhas de forma paginada\r\n  Para nave" +
                "gar pelos resultados de maneira previsível"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ListagemCampanhas.feature"
#line hidden
        
        public ListagemDeCampanhasFeature(ListagemDeCampanhasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar campanhas administrativas com metadados de paginação")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de campanhas")]
        [Xunit.TraitAttribute("Description", "Listar campanhas administrativas com metadados de paginação")]
        public async System.Threading.Tasks.Task ListarCampanhasAdministrativasComMetadadosDePaginacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar campanhas administrativas com metadados de paginação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("existem 3 campanhas com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.WhenAsync("eu listar a página 2 com tamanho 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 11
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 12
    await testRunner.AndAsync("a página retornada deve ser 2 com tamanho 2 e total 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("a listagem deve conter 1 item", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Normalizar paginação inválida")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de campanhas")]
        [Xunit.TraitAttribute("Description", "Normalizar paginação inválida")]
        public async System.Threading.Tasks.Task NormalizarPaginacaoInvalida()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Normalizar paginação inválida", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
    await testRunner.AndAsync("existem 12 campanhas com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 18
    await testRunner.WhenAsync("eu listar a página 0 com tamanho 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 19
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 20
    await testRunner.AndAsync("a página retornada deve ser 1 com tamanho 10 e total 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 21
    await testRunner.AndAsync("a listagem deve conter 10 itens", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por múltiplos status sem duplicar filtros")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de campanhas")]
        [Xunit.TraitAttribute("Description", "Filtrar por múltiplos status sem duplicar filtros")]
        public async System.Threading.Tasks.Task FiltrarPorMultiplosStatusSemDuplicarFiltros()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por múltiplos status sem duplicar filtros", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
    await testRunner.AndAsync("existem 2 campanhas com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 26
    await testRunner.AndAsync("existem 1 campanhas com status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 27
    await testRunner.AndAsync("existem 1 campanhas com status \"Canceled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 28
    await testRunner.WhenAsync("eu listar filtrando pelos status \"Active,Completed,Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 29
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 30
    await testRunner.AndAsync("a página retornada deve ser 1 com tamanho 10 e total 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 31
    await testRunner.AndAsync("a listagem deve conter somente os status \"Active,Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todas as campanhas sem filtro")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de campanhas")]
        [Xunit.TraitAttribute("Description", "Listar todas as campanhas sem filtro")]
        public async System.Threading.Tasks.Task ListarTodasAsCampanhasSemFiltro()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar todas as campanhas sem filtro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("que estou autenticado como \"GestorONG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 35
    await testRunner.AndAsync("existem 1 campanhas com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 36
    await testRunner.AndAsync("existem 1 campanhas com status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 37
    await testRunner.AndAsync("existem 1 campanhas com status \"Canceled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 38
    await testRunner.WhenAsync("eu listar as campanhas administrativas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 39
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 40
    await testRunner.AndAsync("a página retornada deve ser 1 com tamanho 10 e total 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Transparência é pública, paginada e contém somente campanhas ativas")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de campanhas")]
        [Xunit.TraitAttribute("Description", "Transparência é pública, paginada e contém somente campanhas ativas")]
        public async System.Threading.Tasks.Task TransparenciaEPublicaPaginadaEContemSomenteCampanhasAtivas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Transparência é pública, paginada e contém somente campanhas ativas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
    await testRunner.GivenAsync("que não estou autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 44
    await testRunner.AndAsync("existem 2 campanhas com status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 45
    await testRunner.AndAsync("existem 1 campanhas com status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 46
    await testRunner.WhenAsync("eu consultar a transparência", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 47
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 48
    await testRunner.AndAsync("a página retornada deve ser 1 com tamanho 10 e total 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 49
    await testRunner.AndAsync("a listagem de transparência deve conter somente campanhas ativas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ListagemDeCampanhasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ListagemDeCampanhasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
